services:
  - type: web
    name: bijo-backend
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: uvicorn backend.app.main:app --host 0.0.0.0 --port 10000
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.4